import turtle
turtle.penup()
turtle.setposition(0,0)
turtle.pendown()
turtle.pencolor("red")
turtle.circle(80)
turtle.penup()
turtle.setposition(-200,-200)
turtle.pendown()
turtle.pencolor("green")
turtle.circle(155)
